### ISSUE TITLE
Including Color (RGB) or other features

### ISSUE THREAD

**Issue by ShadiZaki** [hehefan/P4Transformer#14]
Hi, I'm just curious if it's possible to add color information in the form of RGB channels, or even other point-wise features, as input to the model. And, if it is, what kind of modifications would be required on the model architecture. Is it possible/logical to just add extra channels so that instead of passing xyz tensors, we could feed the model the stacked xyzrgb tensors.

Thanks.

**Comment by hehefan** [comment]
Hi,

You need to set the in_plane hyperparameter in https://github.com/hehefan/P4Transformer/blob/main/models/msr.py#L25 (as well as other models) to the number of the RGB or feature channels. Because no feature was used, in_planes was set to  0 in the code.

Best regards.
