### ISSUE TITLE
Could you release the model for NTU 60 dataset?

### ISSUE THREAD

**Issue by liujiaheng** [hehefan/P4Transformer#5]
I have seen the model for MSR dataset. Are there any differences between the models of MSR and NTU datasets?

**Comment by yuxumin** [comment]
Same question here. Could the author release the code about NTU 60/120?

**Comment by hehefan** [comment]
Hi,

The NUT model is similar to the MAR-Action3D model. There are only a few differences about hypermeters.

Best.

**Comment by SheldongChen** [comment]
Hi,
Your p4Trans work is very meaningful.

We know that the NTU model is similar to the MAR-Action3D model. But can you tell us which hyperparameters have changed?  According to the results that we have reproduced so far, the accuracy of using P4trans on NTU60 (Subject setting) is only 84%. We want to know what goes wrong? I look forward to your reply as soon as possible. Please simply list the hyperparameters that need to be modified under this issue.

Looking forward to your reply.

**Comment by hehefan** [comment]
Hi @SheldongChen,

Not sure how you did it. The code is released. 

Best.
