### ISSUE TITLE
About pretrained model

### ISSUE THREAD

**Issue by yzheng97** [hehefan/P4Transformer#6]
Could you please share the pretrained segmentation model on the Synthia4D dataset? Many thanks!

**Comment by hehefan** [comment]
Hi,

Sorry for my late reply.  I will release the pre-trained model soon.

Best regards.

**Comment by yzheng97** [comment]
Thanks for your reply!

**Comment by hehefan** [comment]
Hi @yzheng97,

Please find the pre-trained Synthia4D model via the link https://drive.google.com/file/d/1-hNUDrHNgX13vz7WOgd3y3zNTarvvgxj/view?usp=sharing

Best regards.

**Comment by yzheng97** [comment]
> Hi @yzheng97,
> 
> Please find the pre-trained Synthia4D model via the link https://drive.google.com/file/d/1-hNUDrHNgX13vz7WOgd3y3zNTarvvgxj/view?usp=sharing
> 
> Best regards.

Many thanks!
