### ISSUE TITLE
Training dataset

### ISSUE THREAD

**Issue by xhsheng-ustc** [hehefan/P4Transformer#7]
Hi, 

Can you release your pre-processed training dataset in point cloud format?

Best Regards

**Comment by hehefan** [comment]
Hi,

For MSR-Action3D and Synthia 4D, please refer to the MeteorNet work.

For NTU, the datasets are too large. Please refer to the 3DV work or the [scripts](https://github.com/hehefan/Point-Spatio-Temporal-Convolution/tree/main/scripts)  for pre-processing.

Best.
