### ISSUE TITLE
About some problems abdout NTU60

### ISSUE THREAD

**Issue by yangtianjin** [hehefan/P4Transformer#8]
Can you provide some code about ntu60, we have some problems when reproducing

**Comment by SheldongChen** [comment]
I was also unable to reproduce the results of the paper on the NTU dataset using p4trans

**Comment by hehefan** [comment]
Hi,

The NTU 60 code will be released to [PST-Transfomer](https://github.com/hehefan/PST-Transformer) after the work is published. Please kindly watch the repo. 

Best regards.

**Comment by SheldongChen** [comment]
> Can you provide some code about ntu60, we have some problems when reproducing

Hi, have you reproduced the code about ntu60 successfully now?

**Comment by hehefan** [comment]
Code released.
