### ISSUE TITLE
Transfer of points to nearest frames

### ISSUE THREAD

**Issue by sheshap** [hehefan/P4Transformer#9]
@hehefan 

Can you please explain what does transfer of points to nearest frames mean?
how are they transferred? (I understand those anchor points are picked using Farthest point sampling)

![image](https://user-images.githubusercontent.com/2320460/152890424-3fe1ffc0-b0eb-454c-999e-e6570f60c809.png)

Thanks in Advance.

**Comment by hehefan** [comment]
Hi,

Anchor points are picked using Farthest point sampling from anchor frames and then transferred (copied) to the nearest frames.

**Comment by sheshap** [comment]
@hehefan 

Thanks for your reply.
Can you please elaborate a little more?

When we do Farthest Point Sampling (FPS) on anchor frames we know the indices in the array of 3D points.
Since points are unordered, how would copying to the nearest frames would help get FPSs points in those nearest frames?

or

By copying how do we know where the points are actually in 3D? (they could be anywhere in the next frame because they are unordered)

Thanks in advance.

**Comment by hehefan** [comment]
Hi @sheshap,

The method is point-based. Point coordinates are always maintained and used for position. When transferring a point to the nearest frames, both the point coordinate and feature are copied.
